<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-07 09:58
=======
# Generated by Django 5.1.7 on 2025-04-06 09:24
>>>>>>> 15cec77dde070bf51d70866b6249d406a96f8e64

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='LocalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=100, unique=True)),
=======
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
>>>>>>> 15cec77dde070bf51d70866b6249d406a96f8e64
                ('user_pw', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
<<<<<<< HEAD
                'abstract': False,
=======
                'db_table': 'user',
                'managed': False,
>>>>>>> 15cec77dde070bf51d70866b6249d406a96f8e64
            },
        ),
    ]
