# Generated by Django 5.2 on 2025-05-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='localuser',
            name='password',
        ),
    ]
