# Generated by Django 5.2 on 2025-05-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_localuser_last_login_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='localuser',
            table='user',
        ),
    ]
