# Generated by Django 5.2 on 2025-05-18 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_localuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=10)),
                ('coin_amount', models.FloatField()),
                ('coin_price', models.FloatField()),
                ('total_value', models.FloatField()),
                ('trade_time', models.DateTimeField(auto_now_add=True)),
                ('money', models.FloatField()),
            ],
            options={
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='coin_archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=10)),
                ('opening_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('trade_price', models.FloatField()),
                ('time_stamp', models.DateTimeField()),
                ('candle_acc_trade_price', models.FloatField()),
                ('candle_acc_trade_volume', models.FloatField()),
                ('candle_time_kst', models.DateTimeField(auto_now_add=True)),
                ('interval', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'coin_archive',
            },
        ),
        migrations.CreateModel(
            name='coin_recent',
            fields=[
                ('coin_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('opening_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('trade_price', models.FloatField()),
                ('time_stamp', models.DateTimeField()),
                ('candle_acc_trade_price', models.FloatField()),
                ('candle_acc_trade_volume', models.FloatField()),
                ('candle_time_kst', models.DateTimeField(auto_now_add=True)),
                ('interval', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'coin_recent',
            },
        ),
        migrations.CreateModel(
            name='trade_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=10)),
                ('coin_price', models.FloatField()),
                ('coin_amount', models.FloatField()),
                ('order_time', models.DateTimeField()),
                ('trade_time', models.DateTimeField(auto_now_add=True)),
                ('is_deal', models.BooleanField(default=False)),
                ('trade_fee', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'trade_history',
            },
        ),
        migrations.CreateModel(
            name='trade_order_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=10)),
                ('coin_price', models.FloatField()),
                ('coin_amount', models.FloatField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('trade_type', models.CharField(max_length=10)),
                ('order_id', models.FloatField(unique=True)),
            ],
            options={
                'db_table': 'trade_request',
            },
        ),
        migrations.AddIndex(
            model_name='localuser',
            index=models.Index(fields=['user_id'], name='user_user_id_31c9cf_idx'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.localuser'),
        ),
        migrations.AddIndex(
            model_name='coin_archive',
            index=models.Index(fields=['coin_name', 'time_stamp'], name='coin_archiv_coin_na_eaa4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='coin_recent',
            index=models.Index(fields=['coin_name', 'time_stamp'], name='coin_recent_coin_na_70d127_idx'),
        ),
        migrations.AddField(
            model_name='trade_history',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.localuser'),
        ),
        migrations.AddField(
            model_name='trade_order_request',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.localuser'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['user_id'], name='asset_user_id_bcef9f_idx'),
        ),
        migrations.AddIndex(
            model_name='trade_history',
            index=models.Index(fields=['user_id'], name='trade_histo_user_id_8687dc_idx'),
        ),
        migrations.AddIndex(
            model_name='trade_order_request',
            index=models.Index(fields=['user_id'], name='trade_reque_user_id_5667ec_idx'),
        ),
    ]
