# Generated by Django 5.1.7 on 2025-03-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_register_is_admin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='user',
        ),
    ]
